services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Orelha*
      POSTGRES_DB: sistema_chamados